# Generated by Django 5.0.3 on 2024-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicantuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='resume_file_path',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
